// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qciqhmlpsgoekogluwrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjaXFobWxwc2dvZWtvZ2x1d3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzYyMTcsImV4cCI6MjA1OTIxMjIxN30.egt3CldyNaJ9oE-umM7A777ngpIh6no66ATIJsujZw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);